root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md

redirects:  
    consumers/best-practices: pythnet-price-feeds/best-practices.md
    consume-data/best-practices: pythnet-price-feeds/best-practices.md